#!/bin/bash

GETPKG='sudo pacman -S --noconfirm'

$GETPKG python python-pip xclip tk

$GETPKG firefox chromium tor torbrowser-launcher

sudo pip install selenium tbselenium pyautogui pyperclip

$GETPKG openvpn openconnect


GETAURPKG='yay -S --aur --noconfirm'

$GETAURPKG google-chrome

